In [2]:
import pandas as pd

path = '../data/real_pv/br-pvgen/'
metadata_df = pd.read_csv(path + "metadata.csv")

# print(metadata_df)
inv_cols = ["datetime", "ps_id","total_active_power_w"]
meteo_cols = ["ambient_temperature_celsius", "panel_temperature_celsius", "ghi_irradiance_wm2", "poa_irradiance_wm2"]
joined_cols = meteo_cols + inv_cols
meteo_cols += ["datetime", "ps_id"]
result = None
for pv_id in metadata_df['id'].unique():
    inv_filename = path + 'inverter/' + pv_id + '.csv'
    inv_df = pd.read_csv(inv_filename)
    inv_df["datetime"] = pd.to_datetime(inv_df["datetime"])
    inv_df = inv_df.groupby(["datetime", "ps_id"], as_index=False).agg(total_active_power_w=("total_active_power_w", "sum"))
    inv_df = inv_df[inv_cols]
    #print(pv_id, " inv ", inv_df["datetime"].min(), " - ", inv_df["datetime"].max())
    inv_df = inv_df.set_index(["datetime", "ps_id"])
    
    
    meteo_filename = path + 'meteorological/' + pv_id + '.csv'
    meteo_df = pd.read_csv(meteo_filename)
    meteo_df["datetime"] = pd.to_datetime(meteo_df["datetime"])
    #print(pv_id, " meteo ", meteo_df["datetime"].min(), " - ", meteo_df["datetime"].max())
    meteo_df = meteo_df[meteo_cols]
    meteo_df = meteo_df.set_index(["datetime", "ps_id"])
    
    common_df = inv_df.join(meteo_df)
          
    if result is None:
        result = common_df
    else:
        result = pd.concat([result, common_df])
    



result

PS_001  inv  2024-03-26 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_001  meteo  2024-03-26 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_002  inv  2024-03-26 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_002  meteo  2024-03-26 00:00:00+00:00  -  2025-06-09 23:45:00+00:00

/tmp/ipykernel_1980423/39947260.py:23: DtypeWarning: Columns (0: interpolated_keys_ambient_temperature_celsius, 1: interpolated_keys_ghi_irradiance_wm2, 2: interpolated_keys_gri_irradiance_wm2, 3: interpolated_keys_panel_temperature_celsius, 4: interpolated_keys_poa_irradiance_wm2, 5: interpolated_keys_wind_speed_ms) have mixed types. Specify dtype option on import or set low_memory=False.
  meteo_df = pd.read_csv(meteo_filename)

PS_003  inv  2024-03-26 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_003  meteo  2024-03-26 00:00:00+00:00  -  2025-06-09 23:45:00+00:00

/tmp/ipykernel_1980423/39947260.py:14: DtypeWarning: Columns (0: interpolated_keys_internal_temperature_celsius, 1: interpolated_keys_total_active_power_w, 2: interpolated_keys_total_dc_power_w, 3: interpolated_keys_total_reactive_power_var) have mixed types. Specify dtype option on import or set low_memory=False.
  inv_df = pd.read_csv(inv_filename)

PS_004  inv  2024-03-26 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_004  meteo  2024-03-26 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_005  inv  2024-04-11 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_005  meteo  2024-04-11 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_006  inv  2024-05-09 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_006  meteo  2024-06-05 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_007  inv  2024-05-09 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_007  meteo  2024-05-09 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_008  inv  2024-05-10 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_008  meteo  2024-05-14 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_009  inv  2024-06-10 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_009  meteo  2024-06-10 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_010  inv  2024-06-12 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_010  meteo  2024-06-12 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_011  inv  2024-06-20 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_011  meteo  2024-06-20 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_012  inv  2024-06-21 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_012  meteo  2024-07-04 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_013  inv  2024-07-03 00:00:00+00:00  -  2025-05-31 23:45:00+00:00
PS_013  meteo  2024-07-03 00:00:00+00:00  -  2025-05-31 23:45:00+00:00
PS_014  inv  2024-08-20 00:00:00+00:00  -  2024-12-17 23:45:00+00:00
PS_014  meteo  2024-08-20 00:00:00+00:00  -  2024-12-19 23:45:00+00:00
PS_015  inv  2024-08-21 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_015  meteo  2024-08-13 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_016  inv  2024-09-02 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_016  meteo  2024-11-01 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_017  inv  2024-09-20 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_017  meteo  2024-09-23 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_018  inv  2024-09-20 00:00:00+00:00  -  2025-04-10 23:45:00+00:00
PS_018  meteo  2024-09-23 00:00:00+00:00  -  2025-04-10 23:45:00+00:00
PS_019  inv  2024-09-23 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_019  meteo  2024-09-23 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_020  inv  2024-09-23 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_020  meteo  2024-09-23 00:00:00+00:00  -  2025-06-09 23:45:00+00:00

/tmp/ipykernel_1980423/39947260.py:14: DtypeWarning: Columns (0: interpolated_keys_internal_temperature_celsius, 1: interpolated_keys_total_active_power_w, 2: interpolated_keys_total_dc_power_w, 3: interpolated_keys_total_reactive_power_var) have mixed types. Specify dtype option on import or set low_memory=False.
  inv_df = pd.read_csv(inv_filename)

PS_021  inv  2024-09-23 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_021  meteo  2024-11-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_022  inv  2024-09-23 00:00:00+00:00  -  2025-05-29 23:45:00+00:00
PS_022  meteo  2024-09-23 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_023  inv  2024-09-23 00:00:00+00:00  -  2025-05-30 23:45:00+00:00
PS_023  meteo  2024-09-23 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_024  inv  2024-10-09 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_024  meteo  2024-10-09 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_025  inv  2024-10-02 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_025  meteo  2024-10-03 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_026  inv  2024-09-27 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_026  meteo  2024-09-27 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_027  inv  2024-09-30 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_027  meteo  2024-09-30 00:00:00+00:00  -  2025-04-18 23:45:00+00:00
PS_028  inv  2024-10-01 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_028  meteo  2024-10-01 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_029  inv  2024-09-30 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_029  meteo  2024-10-03 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_030  inv  2024-10-02 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_030  meteo  2024-10-02 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_031  inv  2024-10-04 00:00:00+00:00  -  2025-03-22 23:45:00+00:00
PS_031  meteo  2024-10-04 00:00:00+00:00  -  2025-03-22 23:45:00+00:00
PS_032  inv  2024-10-04 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_032  meteo  2024-10-04 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_033  inv  2024-10-08 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_033  meteo  2024-10-08 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_034  inv  2024-10-10 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_034  meteo  2024-10-10 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_035  inv  2024-11-25 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_035  meteo  2024-11-25 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_036  inv  2024-11-26 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_036  meteo  2024-11-26 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_037  inv  2024-12-02 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_037  meteo  2024-12-03 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_038  inv  2024-12-02 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_038  meteo  2024-12-02 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_039  inv  2024-12-06 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_039  meteo  2024-12-06 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_040  inv  2024-12-19 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_040  meteo  2024-12-19 00:00:00+00:00  -  2025-05-03 23:45:00+00:00
PS_041  inv  2024-12-17 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_041  meteo  2024-12-17 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_042  inv  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_042  meteo  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_043  inv  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_043  meteo  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_044  inv  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_044  meteo  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_045  inv  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_045  meteo  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_046  inv  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_046  meteo  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_047  inv  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_047  meteo  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_048  inv  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_048  meteo  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_049  inv  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_049  meteo  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_050  inv  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_050  meteo  2025-02-28 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_051  inv  2025-03-10 00:00:00+00:00  -  2025-06-09 23:45:00+00:00
PS_051  meteo  2025-03-10 00:00:00+00:00  -  2025-06-09 23:45:00+00:00

,,total_active_power_w,ambient_temperature_celsius,panel_temperature_celsius,ghi_irradiance_wm2,poa_irradiance_wm2
datetime,ps_id,,,,,
2024-03-26 00:00:00+00:00,PS_001,0.0,NaN,NaN,NaN,NaN
2024-03-26 00:15:00+00:00,PS_001,0.0,NaN,NaN,NaN,NaN
2024-03-26 00:30:00+00:00,PS_001,0.0,NaN,NaN,NaN,NaN
2024-03-26 00:45:00+00:00,PS_001,0.0,NaN,NaN,NaN,NaN
2024-03-26 01:00:00+00:00,PS_001,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2025-06-09 22:45:00+00:00,PS_051,0.0,NaN,NaN,NaN,NaN
2025-06-09 23:00:00+00:00,PS_051,0.0,NaN,NaN,NaN,NaN
2025-06-09 23:15:00+00:00,PS_051,0.0,NaN,NaN,NaN,NaN
2025-06-09 23:30:00+00:00,PS_051,0.0,NaN,NaN,NaN,NaN
2025-06-09 23:45:00+00:00,PS_051,0.0,NaN,NaN,NaN,NaN

In [3]:
result = result.reset_index()
result = result.dropna()

In [4]:
print(result.isnull().sum(axis=0))

result[(result['total_active_power_w'] > 5e5) & (result['ps_id'] == "PS_001")]

datetime                       0
ps_id                          0
total_active_power_w           0
ambient_temperature_celsius    0
panel_temperature_celsius      0
ghi_irradiance_wm2             0
poa_irradiance_wm2             0
dtype: int64

,datetime,ps_id,total_active_power_w,ambient_temperature_celsius,panel_temperature_celsius,ghi_irradiance_wm2,poa_irradiance_wm2
242,2024-03-28 12:30:00+00:00,PS_001,8.472500e+05,20.949042,20.757043,178.682977,164.524503
243,2024-03-28 12:45:00+00:00,PS_001,1.401623e+06,21.017458,20.436287,200.058878,195.136768
244,2024-03-28 13:00:00+00:00,PS_001,1.723051e+06,21.621404,21.721403,320.811897,314.373920
245,2024-03-28 13:15:00+00:00,PS_001,1.976655e+06,21.863892,22.111576,304.648917,287.682595
246,2024-03-28 13:30:00+00:00,PS_001,1.873885e+06,22.408775,23.667327,388.260065,401.701775
...,...,...,...,...,...,...,...
42313,2025-06-09 18:15:00+00:00,PS_001,3.581014e+06,21.800001,28.062500,520.581228,751.488764
42314,2025-06-09 18:30:00+00:00,PS_001,1.702499e+06,22.500000,33.600000,268.839993,433.570000
42315,2025-06-09 18:45:00+00:00,PS_001,1.473602e+06,22.175001,31.125000,177.866251,243.459993
42316,2025-06-09 19:00:00+00:00,PS_001,1.139750e+06,21.362500,26.525000,152.423748,173.681255
42317,2025-06-09 19:15:00+00:00,PS_001,5.158570e+05,21.158580,25.444378,126.410888,139.397811

In [5]:
result.to_parquet(path + "merged.parquet")

In [6]:
df = pd.read_parquet(path + "merged.parquet")
df

,datetime,ps_id,total_active_power_w,ambient_temperature_celsius,panel_temperature_celsius,ghi_irradiance_wm2,poa_irradiance_wm2
index,,,,,,,
69,2024-03-26 17:15:00+00:00,PS_001,4.055110e+05,23.000000,23.503323,96.539849,98.582374
70,2024-03-26 17:30:00+00:00,PS_001,8.395200e+04,22.960714,23.114820,53.623824,51.219068
71,2024-03-26 17:45:00+00:00,PS_001,1.457120e+05,21.767193,21.019041,14.290886,11.143078
72,2024-03-26 18:00:00+00:00,PS_001,2.090670e+05,20.596816,19.851180,33.510205,28.554051
73,2024-03-26 18:15:00+00:00,PS_001,2.729760e+05,20.431653,19.900000,50.439045,40.336890
...,...,...,...,...,...,...,...
1206890,2025-06-09 18:30:00+00:00,PS_051,2.235609e+06,34.851252,48.350000,358.443756,800.220009
1206891,2025-06-09 18:45:00+00:00,PS_051,2.072260e+06,34.802081,46.537501,300.378761,713.826256
1206892,2025-06-09 19:00:00+00:00,PS_051,1.732663e+06,34.334583,42.137500,245.017496,590.638741
1206893,2025-06-09 19:15:00+00:00,PS_051,1.545858e+06,34.561507,42.260098,210.476013,510.536055
1206894,2025-06-09 19:30:00+00:00,PS_051,0.000000e+00,34.589996,42.299999,206.910004,502.119995